// GENERATED by scripts/optimize-assets.mjs from the art build's trim_layout.json. Do not edit.
// Trim-sheet rows as [v0, v1] in glTF UV space (v down, not flipped by GLTFLoader).
export const TRIM_ROWS = {
 "white": [
  0.002,
  0.0918
 ],
 "shutter": [
  0.0957,
  0.1543
 ],
 "red": [
  0.1582,
  0.2168
 ],
 "glass": [
  0.2207,
  0.2793
 ],
 "metal": [
  0.2832,
  0.3418
 ],
 "brick": [
  0.3457,
  0.4043
 ],
 "stone": [
  0.4082,
  0.4668
 ],
 "alu": [
  0.4707,
  0.5293
 ],
 "interior": [
  0.5332,
  0.5918
 ],
 "navy": [
  0.5957,
  0.6543
 ],
 "teak": [
  0.6582,
  0.7168
 ],
 "canvas": [
  0.7207,
  0.7793
 ],
 "concrete": [
  0.7832,
  0.8418
 ],
 "green": [
  0.8457,
  0.873
 ],
 "yellow": [
  0.877,
  0.9043
 ],
 "copper": [
  0.9082,
  0.9355
 ],
 "driftwood": [
  0.9395,
  0.9668
 ],
 "limestone": [
  0.9707,
  0.998
 ]
};
